import {
  BankAccount,
  BillItem,
  Contact,
  DealOffer,
  FixedDepositItem,
  MerchantQr,
  NotificationItem,
  RechargePlan,
  SuperCardInfo,
  Transaction,
} from '../types';

export const INITIAL_BANKS: BankAccount[] = [
  {
    id: 'bank-hdfc',
    bankName: 'HDFC Bank',
    logo: 'HDFC',
    accountNumberMasked: 'XXXXXX4829',
    accountType: 'Savings',
    balance: 24850.50,
    isPrimary: true,
    upiId: 'rahul.sharma@paynow',
  },
  {
    id: 'bank-icici',
    bankName: 'ICICI Bank',
    logo: 'ICICI',
    accountNumberMasked: 'XXXXXX9102',
    accountType: 'Savings',
    balance: 8320.00,
    isPrimary: false,
    upiId: 'rahul.icici@paynow',
  },
  {
    id: 'bank-sbi',
    bankName: 'State Bank of India',
    logo: 'SBI',
    accountNumberMasked: 'XXXXXX1154',
    accountType: 'Savings',
    balance: 3500.00,
    isPrimary: false,
    upiId: 'rahul.sbi@paynow',
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'c1',
    name: 'Priya Patel',
    phone: '+91 98201 44521',
    upiId: 'priya.patel@okhdfcbank',
    avatarBg: 'bg-emerald-600',
    initials: 'PP',
    isRecent: true,
  },
  {
    id: 'c2',
    name: 'Deepak Sharma',
    phone: '+91 99104 88392',
    upiId: 'deepak.s@paynow',
    avatarBg: 'bg-indigo-600',
    initials: 'DS',
    isRecent: true,
  },
  {
    id: 'c3',
    name: 'Ananya Iyer',
    phone: '+91 97412 39014',
    upiId: 'ananya.iyer@okaxis',
    avatarBg: 'bg-purple-600',
    initials: 'AI',
    isRecent: true,
  },
  {
    id: 'c4',
    name: 'Rohit Verma',
    phone: '+91 98110 59283',
    upiId: 'rohitv@paynow',
    avatarBg: 'bg-amber-600',
    initials: 'RV',
    isRecent: true,
  },
  {
    id: 'c5',
    name: 'Vikram Malhotra',
    phone: '+91 98450 19284',
    upiId: 'vikram.m@oksbi',
    avatarBg: 'bg-blue-600',
    initials: 'VM',
    isRecent: false,
  },
  {
    id: 'c6',
    name: 'Sneha Roy',
    phone: '+91 99805 77123',
    upiId: 'sneha.roy@paynow',
    avatarBg: 'bg-rose-600',
    initials: 'SR',
    isRecent: false,
  },
];

export const PRESET_MERCHANTS: MerchantQr[] = [
  {
    id: 'm1',
    name: 'Chai Point Koramangala',
    category: 'Cafe & Snacks',
    upiId: 'chaipoint@icici',
    defaultAmount: 85,
    note: 'Ginger tea & samosa',
    verified: true,
    avatarBg: 'bg-amber-500',
  },
  {
    id: 'm2',
    name: 'Swiggy Instamart',
    category: 'Groceries & Quick',
    upiId: 'swiggyinstamart@axisbank',
    defaultAmount: 340,
    note: 'Fresh milk, bread & fruit',
    verified: true,
    avatarBg: 'bg-orange-500',
  },
  {
    id: 'm3',
    name: 'Blue Tokai Coffee Roasters',
    category: 'Specialty Coffee',
    upiId: 'bluetokai@yesbank',
    defaultAmount: 260,
    note: 'Iced Americano & cookie',
    verified: true,
    avatarBg: 'bg-blue-700',
  },
  {
    id: 'm4',
    name: 'Namma Metro Bangalore',
    category: 'Transit & Commute',
    upiId: 'bmrcl.metro@sbi',
    defaultAmount: 45,
    note: 'Single trip QR ticket',
    verified: true,
    avatarBg: 'bg-purple-600',
  },
  {
    id: 'm5',
    name: 'Starbucks Reserve',
    category: 'Dining & Beverages',
    upiId: 'starbucksindia@hdfcbank',
    defaultAmount: 410,
    note: 'Cold brew & croissant',
    verified: true,
    avatarBg: 'bg-emerald-700',
  },
  {
    id: 'm6',
    name: 'Cult.fit Fitness Hub',
    category: 'Health & Fitness',
    upiId: 'cultfit@hdfcbank',
    defaultAmount: 1200,
    note: 'Monthly workout day-pass',
    verified: true,
    avatarBg: 'bg-red-500',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    upiRefNumber: 'UPI/428901239014',
    type: 'debit',
    title: 'Chai Point Koramangala',
    subtitle: 'Paid via HDFC · **4829',
    upiId: 'chaipoint@icici',
    amount: 85,
    cashback: 4.25,
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(), // 35 mins ago
    status: 'SUCCESS',
    category: 'food',
    bankAccountId: 'bank-hdfc',
    note: 'Evening tea break',
  },
  {
    id: 'tx-2',
    upiRefNumber: 'UPI/428900891278',
    type: 'debit',
    title: 'Swiggy Instamart',
    subtitle: 'Paid via HDFC · **4829',
    upiId: 'swiggyinstamart@axisbank',
    amount: 420,
    cashback: 21.0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), // 3 hours ago
    status: 'SUCCESS',
    category: 'shopping',
    bankAccountId: 'bank-hdfc',
    note: 'Groceries and snacks',
  },
  {
    id: 'tx-3',
    upiRefNumber: 'UPI/428876129841',
    type: 'credit',
    title: 'Super Cashback Direct Credit',
    subtitle: 'Credited to HDFC Bank A/c **4829',
    upiId: 'cashback@paynow',
    amount: 142.50,
    cashback: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), // Yesterday
    status: 'SUCCESS',
    category: 'cashback',
    bankAccountId: 'bank-hdfc',
    note: 'Real cash deposited direct to bank',
  },
  {
    id: 'tx-4',
    upiRefNumber: 'UPI/428812984102',
    type: 'debit',
    title: 'Priya Patel',
    subtitle: 'Transfer to priya.patel@okhdfcbank',
    upiId: 'priya.patel@okhdfcbank',
    amount: 650,
    cashback: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(), // Yesterday
    status: 'SUCCESS',
    category: 'transfer',
    bankAccountId: 'bank-hdfc',
    note: 'Dinner bill split 🍕',
  },
  {
    id: 'tx-5',
    upiRefNumber: 'UPI/428711094821',
    type: 'debit',
    title: 'Blue Tokai Coffee Roasters',
    subtitle: 'Paid via HDFC · **4829',
    upiId: 'bluetokai@yesbank',
    amount: 260,
    cashback: 13.0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(), // 2 days ago
    status: 'SUCCESS',
    category: 'food',
    bankAccountId: 'bank-hdfc',
    note: 'Cold brew & cookie',
  },
  {
    id: 'tx-6',
    upiRefNumber: 'UPI/428612984920',
    type: 'debit',
    title: 'BESCOM Electricity Bill',
    subtitle: 'Paid via HDFC · **4829',
    upiId: 'bescom@axisbank',
    amount: 1480,
    cashback: 44.40,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(), // 4 days ago
    status: 'SUCCESS',
    category: 'bills',
    bankAccountId: 'bank-hdfc',
    note: 'Monthly power utility',
  },
  {
    id: 'tx-7',
    upiRefNumber: 'UPI/428510293841',
    type: 'credit',
    title: 'Ananya Iyer',
    subtitle: 'Received via UPI · ananya.iyer@okaxis',
    upiId: 'ananya.iyer@okaxis',
    amount: 1500,
    cashback: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    status: 'SUCCESS',
    category: 'transfer',
    bankAccountId: 'bank-hdfc',
    note: 'Weekend roadtrip split payment',
  },
  {
    id: 'tx-8',
    upiRefNumber: 'UPI/428409182736',
    type: 'debit',
    title: 'Amazon Shopping',
    subtitle: 'Failed · Bank server decline',
    upiId: 'amazonpay@icici',
    amount: 1899,
    cashback: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 140).toISOString(),
    status: 'FAILED',
    category: 'shopping',
    bankAccountId: 'bank-hdfc',
    note: 'Wireless earbuds order (declined by bank)',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '🎉 ₹21.00 Instant Cashback Credited!',
    message: 'Your 5% real cashback for Swiggy Instamart has been credited directly to HDFC A/c **4829.',
    timestamp: '15m ago',
    read: false,
    type: 'cashback',
    amount: 21.00,
  },
  {
    id: 'notif-2',
    title: 'Payment Successful to Chai Point',
    message: '₹85.00 paid securely via UPI Ref UPI/428901239014.',
    timestamp: '35m ago',
    read: false,
    type: 'payment',
  },
  {
    id: 'notif-3',
    title: '🔥 Super Cashback 5% Unlocked',
    message: 'Scan any merchant QR code to earn flat 5% cashback straight into your bank account.',
    timestamp: '2h ago',
    read: true,
    type: 'offer',
  },
];

export const OPERATOR_PLANS: Record<string, RechargePlan[]> = {
  Jio: [
    {
      id: 'jio-299',
      price: 299,
      validity: '28 Days',
      data: '2.0 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 14.95,
      description: 'Unlimited 5G Data included + 100 SMS/day + JioTV & JioCinema apps.',
      ottBadges: ['JioCinema', '5G Free'],
    },
    {
      id: 'jio-349',
      price: 349,
      validity: '28 Days',
      data: '2.5 GB / Day',
      voice: 'Truly Unlimited',
      category: '5G Unlimited',
      cashback: 17.45,
      description: 'True 5G Unlimited data with high-speed browsing.',
      ottBadges: ['True 5G', 'JioCloud'],
    },
    {
      id: 'jio-666',
      price: 666,
      validity: '70 Days',
      data: '1.5 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 33.30,
      description: 'Best-value quarterly pack. 105 GB total data with nationwide roaming.',
      ottBadges: ['Super Saver'],
    },
    {
      id: 'jio-899',
      price: 899,
      validity: '90 Days',
      data: '2.0 GB / Day + 20GB extra',
      voice: 'Truly Unlimited',
      category: 'Entertainment',
      cashback: 44.95,
      description: 'Disney+ Hotstar 3-month Mobile subscription + unlimited 5G.',
      ottBadges: ['Hotstar', '20GB Extra'],
    },
    {
      id: 'jio-3599',
      price: 3599,
      validity: '365 Days',
      data: '2.5 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Annual',
      cashback: 179.95,
      description: 'Full year freedom. Unlimited 5G, 100 SMS/day + Amazon Prime Lite.',
      ottBadges: ['Annual Pass', 'Prime Lite'],
    },
  ],
  Airtel: [
    {
      id: 'airtel-299',
      price: 299,
      validity: '28 Days',
      data: '1.5 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 14.95,
      description: 'Unlimited 5G Data, Wynk Music & Apollo 24|7 Circle subscription.',
      ottBadges: ['Wynk', '5G'],
    },
    {
      id: 'airtel-399',
      price: 399,
      validity: '28 Days',
      data: '3.0 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Entertainment',
      cashback: 19.95,
      description: 'Unlimited 5G + Disney+ Hotstar Mobile 3 months included.',
      ottBadges: ['Hotstar', '3GB/Day'],
    },
    {
      id: 'airtel-799',
      price: 799,
      validity: '77 Days',
      data: '1.5 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 39.95,
      description: 'Unlimited local, STD and roaming calls with unlimited 5G.',
      ottBadges: ['Popular'],
    },
    {
      id: 'airtel-3599',
      price: 3599,
      validity: '365 Days',
      data: '2.0 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Annual',
      cashback: 179.95,
      description: 'Annual recharge with 5G Unlimited data and free Hello Tunes.',
      ottBadges: ['Annual', 'Unlimited 5G'],
    },
  ],
  Vi: [
    {
      id: 'vi-299',
      price: 299,
      validity: '28 Days',
      data: '1.5 GB / Day + Binge All Night',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 14.95,
      description: 'Free surfing from 12 AM to 6 AM without data deduction.',
      ottBadges: ['Night Free', 'Rollover'],
    },
    {
      id: 'vi-479',
      price: 479,
      validity: '56 Days',
      data: '1.5 GB / Day',
      voice: 'Truly Unlimited',
      category: 'Popular',
      cashback: 23.95,
      description: 'Weekend data rollover + Vi Movies & TV app.',
      ottBadges: ['Rollover'],
    },
  ],
};

export const INITIAL_BILLS: BillItem[] = [
  {
    id: 'bill-bescom',
    billerType: 'electricity',
    billerName: 'BESCOM Electricity Bangalore',
    billerLogo: '⚡',
    consumerNumber: '04-291-88210',
    amount: 1480,
    dueDate: '28 Sep 2026',
    cashback: 29.60,
    billPeriod: 'Aug - Sep 2026',
  },
  {
    id: 'bill-fastag',
    billerType: 'fastag',
    billerName: 'ICICI Bank NETC FASTag',
    billerLogo: '🚗',
    consumerNumber: 'KA-03-NC-8821',
    amount: 500,
    dueDate: 'Low Balance (₹110 left)',
    cashback: 15.00,
    billPeriod: 'Instant Toll Wallet Topup',
  },
  {
    id: 'bill-tataplay',
    billerType: 'dth',
    billerName: 'Tata Play DTH',
    billerLogo: '📺',
    consumerNumber: '3029188471',
    amount: 389,
    dueDate: '30 Sep 2026',
    cashback: 11.67,
    billPeriod: 'Ultra HD Monthly Pack',
  },
  {
    id: 'bill-airtelfiber',
    billerType: 'broadband',
    billerName: 'Airtel Xstream Fiber',
    billerLogo: '🌐',
    consumerNumber: '080-49182390',
    amount: 943,
    dueDate: '02 Oct 2026',
    cashback: 28.29,
    billPeriod: '200 Mbps Unlimited Fiber',
  },
  {
    id: 'bill-hdfccard',
    billerType: 'creditcard',
    billerName: 'HDFC Regalia Gold Credit Card',
    billerLogo: '💳',
    consumerNumber: '•••• •••• •••• 4920',
    amount: 12450,
    dueDate: '05 Oct 2026',
    cashback: 100.00,
    billPeriod: 'Statement Due (Min ₹1,200)',
  },
  {
    id: 'bill-gascity',
    billerType: 'gas',
    billerName: 'GAIL Gas Piped Pipeline',
    billerLogo: '🔥',
    consumerNumber: 'GAIL-891024',
    amount: 620,
    dueDate: '04 Oct 2026',
    cashback: 12.40,
    billPeriod: 'Bi-monthly Domestic Consumption',
  },
];

export const INITIAL_SUPER_CARD: SuperCardInfo = {
  cardNumberMasked: '4532 •••• •••• 8824',
  cardHolder: 'RAHUL SHARMA',
  expiry: '08/30',
  cvv: '742',
  totalLimit: 100000,
  availableLimit: 87520,
  usedLimit: 12480,
  minDue: 1200,
  dueDate: '15 Oct 2026',
  cashbackEarnedThisCycle: 624.00,
  isFrozen: false,
  network: 'RuPay',
};

export const INITIAL_SUPER_FDS: FixedDepositItem[] = [
  {
    id: 'fd-1',
    fdNumber: 'FD/2026/89124',
    bankName: 'Shivalik Small Finance Bank',
    principal: 25000,
    interestRate: 9.1,
    tenureMonths: 12,
    maturityAmount: 27275,
    maturityDate: '18 Sep 2027',
    status: 'Active',
    rbiInsured: true,
  },
  {
    id: 'fd-2',
    fdNumber: 'FD/2026/51290',
    bankName: 'Suryoday Small Finance Bank',
    principal: 50000,
    interestRate: 9.5,
    tenureMonths: 24,
    maturityAmount: 60120,
    maturityDate: '12 Jan 2028',
    status: 'Active',
    rbiInsured: true,
  },
];

export const DEAL_OFFERS: DealOffer[] = [
  {
    id: 'deal-starbucks',
    brand: 'Starbucks',
    logo: '☕',
    bannerBg: 'from-emerald-900 to-green-950',
    title: 'Flat ₹50 Instant Cashback',
    highlight: 'On orders above ₹250 via Scan & Pay',
    cashbackPercent: 20,
    tag: 'Beverages',
    merchantQr: PRESET_MERCHANTS[4],
  },
  {
    id: 'deal-swiggy',
    brand: 'Swiggy Instamart',
    logo: '🍊',
    bannerBg: 'from-orange-900 to-amber-950',
    title: '10% Real Cash Deposit',
    highlight: 'Valid on grocery and daily staples',
    cashbackPercent: 10,
    tag: 'Groceries',
    merchantQr: PRESET_MERCHANTS[1],
  },
  {
    id: 'deal-chai',
    brand: 'Chai Point',
    logo: '🍵',
    bannerBg: 'from-amber-900 to-stone-900',
    title: 'Flat ₹15 on Morning Tea',
    highlight: 'Earned right at the billing counter',
    cashbackPercent: 15,
    tag: 'Quick Bites',
    merchantQr: PRESET_MERCHANTS[0],
  },
  {
    id: 'deal-bluetokai',
    brand: 'Blue Tokai Roasters',
    logo: '☕',
    bannerBg: 'from-blue-900 to-indigo-950',
    title: 'Flat ₹30 on Specialty Brews',
    highlight: 'Instant credit into HDFC savings A/c',
    cashbackPercent: 12,
    tag: 'Specialty Coffee',
    merchantQr: PRESET_MERCHANTS[2],
  },
];

export interface SupportedBankInfo {
  id: string;
  name: string;
  shortName: string;
  color: string;
  isPopular?: boolean;
}

export const ALL_INDIAN_BANKS: SupportedBankInfo[] = [
  { id: 'sbi', name: 'State Bank of India', shortName: 'SBI', color: 'from-blue-600 to-sky-500', isPopular: true },
  { id: 'hdfc', name: 'HDFC Bank', shortName: 'HDFC', color: 'from-blue-800 to-indigo-900', isPopular: true },
  { id: 'icici', name: 'ICICI Bank', shortName: 'ICICI', color: 'from-orange-600 to-red-600', isPopular: true },
  { id: 'axis', name: 'Axis Bank', shortName: 'AXIS', color: 'from-rose-800 to-pink-700', isPopular: true },
  { id: 'kotak', name: 'Kotak Mahindra Bank', shortName: 'KOTAK', color: 'from-red-700 to-rose-600', isPopular: true },
  { id: 'pnb', name: 'Punjab National Bank', shortName: 'PNB', color: 'from-amber-600 to-yellow-600', isPopular: true },
  { id: 'bob', name: 'Bank of Baroda', shortName: 'BOB', color: 'from-orange-500 to-amber-600', isPopular: true },
  { id: 'canara', name: 'Canara Bank', shortName: 'CANARA', color: 'from-blue-500 to-cyan-500', isPopular: false },
  { id: 'union', name: 'Union Bank of India', shortName: 'UBI', color: 'from-blue-700 to-indigo-600', isPopular: false },
  { id: 'boi', name: 'Bank of India', shortName: 'BOI', color: 'from-red-600 to-orange-500', isPopular: false },
  { id: 'indian', name: 'Indian Bank', shortName: 'IB', color: 'from-blue-600 to-teal-600', isPopular: false },
  { id: 'central', name: 'Central Bank of India', shortName: 'CBI', color: 'from-sky-700 to-blue-800', isPopular: false },
  { id: 'idbi', name: 'IDBI Bank', shortName: 'IDBI', color: 'from-teal-600 to-emerald-700', isPopular: false },
  { id: 'indusind', name: 'IndusInd Bank', shortName: 'INDUS', color: 'from-rose-900 to-red-800', isPopular: false },
  { id: 'yes', name: 'Yes Bank', shortName: 'YES', color: 'from-blue-600 to-indigo-700', isPopular: false },
  { id: 'federal', name: 'Federal Bank', shortName: 'FED', color: 'from-amber-700 to-yellow-800', isPopular: false },
  { id: 'idfc', name: 'IDFC FIRST Bank', shortName: 'IDFC', color: 'from-red-800 to-rose-900', isPopular: false },
  { id: 'rbl', name: 'RBL Bank', shortName: 'RBL', color: 'from-blue-900 to-indigo-900', isPopular: false },
  { id: 'southindian', name: 'South Indian Bank', shortName: 'SIB', color: 'from-red-700 to-rose-700', isPopular: false },
  { id: 'bandhan', name: 'Bandhan Bank', shortName: 'BANDHAN', color: 'from-red-600 to-orange-600', isPopular: false },
  { id: 'au', name: 'AU Small Finance Bank', shortName: 'AU', color: 'from-purple-700 to-indigo-800', isPopular: false },
  { id: 'paytm', name: 'Paytm Payments Bank', shortName: 'PAYTM', color: 'from-sky-600 to-blue-700', isPopular: false },
  { id: 'airtel', name: 'Airtel Payments Bank', shortName: 'AIRTEL', color: 'from-red-600 to-rose-600', isPopular: false },
  { id: 'iob', name: 'Indian Overseas Bank', shortName: 'IOB', color: 'from-blue-800 to-cyan-700', isPopular: false },
  { id: 'uco', name: 'UCO Bank', shortName: 'UCO', color: 'from-blue-700 to-sky-700', isPopular: false },
];

